// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


void ui_SettingAlarm_screen_init(void)
{
    ui_SettingAlarm = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingAlarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings1 = lv_label_create(ui_SettingAlarm);
    lv_obj_set_width(ui_Settings1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings1, 0);
    lv_obj_set_y(ui_Settings1, -96);
    lv_obj_set_align(ui_Settings1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings1, "Settings");
    lv_obj_set_style_text_color(ui_Settings1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Settings1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Settings1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Settings1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Settings1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature1 = lv_label_create(ui_SettingAlarm);
    lv_obj_set_width(ui_Temperature1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature1, 0);
    lv_obj_set_y(ui_Temperature1, -59);
    lv_obj_set_align(ui_Temperature1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature1, "Temperature");
    lv_obj_set_style_text_color(ui_Temperature1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Temperature1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm1 = lv_label_create(ui_SettingAlarm);
    lv_obj_set_width(ui_Alarm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarm1, -6);
    lv_obj_set_y(ui_Alarm1, -19);
    lv_obj_set_align(ui_Alarm1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alarm1, "Alarm");
    lv_obj_set_style_text_color(ui_Alarm1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Alarm1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarm1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateTime1 = lv_label_create(ui_SettingAlarm);
    lv_obj_set_width(ui_DateTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateTime1, -5);
    lv_obj_set_y(ui_DateTime1, 26);
    lv_obj_set_align(ui_DateTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateTime1, "Date/Time");
    lv_obj_set_style_text_color(ui_DateTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DateTime1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateTime1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DataLoging1 = lv_label_create(ui_SettingAlarm);
    lv_obj_set_width(ui_DataLoging1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DataLoging1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DataLoging1, -8);
    lv_obj_set_y(ui_DataLoging1, 59);
    lv_obj_set_align(ui_DataLoging1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DataLoging1, "Data Logging");
    lv_obj_set_style_text_color(ui_DataLoging1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DataLoging1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DataLoging1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DataLoging1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back1 = lv_label_create(ui_SettingAlarm);
    lv_obj_set_width(ui_Back1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back1, -10);
    lv_obj_set_y(ui_Back1, 91);
    lv_obj_set_align(ui_Back1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back1, "Back");
    lv_obj_set_style_text_color(ui_Back1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Back1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Back1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Back1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Back1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
