// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


void ui_SettingTemperature_screen_init(void)
{
    ui_SettingTemperature = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingTemperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings = lv_label_create(ui_SettingTemperature);
    lv_obj_set_width(ui_Settings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings, 0);
    lv_obj_set_y(ui_Settings, -96);
    lv_obj_set_align(ui_Settings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings, "Settings");
    lv_obj_set_style_text_color(ui_Settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Settings, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Settings, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_SettingTemperature);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 1);
    lv_obj_set_y(ui_Temperature, -49);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "Temperature");
    lv_obj_set_style_text_color(ui_Temperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm = lv_label_create(ui_SettingTemperature);
    lv_obj_set_width(ui_Alarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarm, -6);
    lv_obj_set_y(ui_Alarm, -8);
    lv_obj_set_align(ui_Alarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alarm, "Alarm");
    lv_obj_set_style_text_color(ui_Alarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Alarm, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarm, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateTime = lv_label_create(ui_SettingTemperature);
    lv_obj_set_width(ui_DateTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateTime, -5);
    lv_obj_set_y(ui_DateTime, 26);
    lv_obj_set_align(ui_DateTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateTime, "Date/Time");
    lv_obj_set_style_text_color(ui_DateTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DateTime, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateTime, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DataLoging = lv_label_create(ui_SettingTemperature);
    lv_obj_set_width(ui_DataLoging, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DataLoging, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DataLoging, -8);
    lv_obj_set_y(ui_DataLoging, 59);
    lv_obj_set_align(ui_DataLoging, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DataLoging, "Data Logging");
    lv_obj_set_style_text_color(ui_DataLoging, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DataLoging, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DataLoging, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DataLoging, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back = lv_label_create(ui_SettingTemperature);
    lv_obj_set_width(ui_Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back, -10);
    lv_obj_set_y(ui_Back, 91);
    lv_obj_set_align(ui_Back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back, "Back");
    lv_obj_set_style_text_color(ui_Back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Back, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Back, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Back, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
