// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t *ui_Main;
lv_obj_t *ui_SpeakerSymbol;
lv_obj_t *ui_temper;
lv_obj_t *ui_Freezer5;
lv_obj_t *ui_ac;
lv_obj_t *ui_BatSymbol;


// SCREEN: ui_OperationModeScreenFreezer
void ui_OperationModeScreenFreezer_screen_init(void);
lv_obj_t *ui_OperationModeScreenFreezer;
lv_obj_t *ui_OpeartionMode;
lv_obj_t *ui_Fridge;
lv_obj_t *ui_Freezer;
lv_obj_t *ui_Back2;


// SCREEN: ui_OperationModeScreenFridge
void ui_OperationModeScreenFridge_screen_init(void);
lv_obj_t *ui_OperationModeScreenFridge;
lv_obj_t *ui_OpeartionMode1;
lv_obj_t *ui_Fridge1;
lv_obj_t *ui_Freezer1;
lv_obj_t *ui_Back3;


// SCREEN: ui_OperationModeScreenBack
void ui_OperationModeScreenBack_screen_init(void);
lv_obj_t *ui_OperationModeScreenBack;
lv_obj_t *ui_OpeartionMode2;
lv_obj_t *ui_Fridge2;
lv_obj_t *ui_Freezer2;
lv_obj_t *ui_Back4;


// SCREEN: ui_SettingData
void ui_SettingData_screen_init(void);
lv_obj_t *ui_SettingData;
lv_obj_t *ui_SettingsDownloadData;
lv_obj_t *ui_DateTime1;
lv_obj_t *ui_DataLoging1;
lv_obj_t *ui_Back1;


// SCREEN: ui_SettingDateTime
void ui_SettingDateTime_screen_init(void);
lv_obj_t *ui_SettingDateTime;
lv_obj_t *ui_Settings;
lv_obj_t *ui_DateTime;
lv_obj_t *ui_DownloadData;
lv_obj_t *ui_Back;


// SCREEN: ui_SettingDateTimeYear
void ui_SettingDateTimeYear_screen_init(void);
lv_obj_t *ui_SettingDateTimeYear;
lv_obj_t *ui_SetYear;
lv_obj_t *ui_SetMonth;
lv_obj_t *ui_SetDay;
lv_obj_t *ui_Back5;
lv_obj_t *ui_SetHour;
lv_obj_t *ui_SetMinute;


// SCREEN: ui_SettingDateTimeMonth
void ui_SettingDateTimeMonth_screen_init(void);
lv_obj_t *ui_SettingDateTimeMonth;
lv_obj_t *ui_SetYear1;
lv_obj_t *ui_SetMonth1;
lv_obj_t *ui_SetDay1;
lv_obj_t *ui_Back6;
lv_obj_t *ui_SetHour1;
lv_obj_t *ui_SetMinute1;


// SCREEN: ui_SettingDateTimeDay
void ui_SettingDateTimeDay_screen_init(void);
lv_obj_t *ui_SettingDateTimeDay;
lv_obj_t *ui_SetYear2;
lv_obj_t *ui_SetMonth2;
lv_obj_t *ui_SetDay2;
lv_obj_t *ui_Back7;
lv_obj_t *ui_SetHour2;
lv_obj_t *ui_SetMinute2;


// SCREEN: ui_SettingDateTimeHour
void ui_SettingDateTimeHour_screen_init(void);
lv_obj_t *ui_SettingDateTimeHour;
lv_obj_t *ui_SetYear3;
lv_obj_t *ui_SetMonth3;
lv_obj_t *ui_SetDay3;
lv_obj_t *ui_Back8;
lv_obj_t *ui_SetHour3;
lv_obj_t *ui_SetMinute3;


// SCREEN: ui_SettingDateTimeMinute
void ui_SettingDateTimeMinute_screen_init(void);
lv_obj_t *ui_SettingDateTimeMinute;
lv_obj_t *ui_SetYear4;
lv_obj_t *ui_SetMonth4;
lv_obj_t *ui_SetDay4;
lv_obj_t *ui_Back9;
lv_obj_t *ui_SetHour4;
lv_obj_t *ui_SetMinute4;


// SCREEN: ui_ServiceTemperature
void ui_ServiceTemperature_screen_init(void);
lv_obj_t *ui_ServiceTemperature;
lv_obj_t *ui_Service;
lv_obj_t *ui_Temperature;
lv_obj_t *ui_Alarms;
lv_obj_t *ui_Back10;
lv_obj_t *ui_DataLogging;
lv_obj_t *ui_Calibrartion;


// SCREEN: ui_ServiceTemperatureFreezer
void ui_ServiceTemperatureFreezer_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFreezer;
lv_obj_t *ui_Temperature1;
lv_obj_t *ui_Fridge3;
lv_obj_t *ui_Freezer3;
lv_obj_t *ui_Back11;


// SCREEN: ui_ServiceTemperatureFridge
void ui_ServiceTemperatureFridge_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFridge;
lv_obj_t *ui_Temperature2;
lv_obj_t *ui_Fridge4;
lv_obj_t *ui_Freezer4;
lv_obj_t *ui_Back12;


// SCREEN: ui_ServiceTemperatureFridgeSetpoint
void ui_ServiceTemperatureFridgeSetpoint_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFridgeSetpoint;
lv_obj_t *ui_FridgeManu;
lv_obj_t *ui_SetPoint;
lv_obj_t *ui_TemperatureValue;
lv_obj_t *ui_Back13;


// SCREEN: ui_ServiceTemperatureFridgeSetTem
void ui_ServiceTemperatureFridgeSetTem_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFridgeSetTem;
lv_obj_t *ui_FridgeManu1;
lv_obj_t *ui_SetPoint1;
lv_obj_t *ui_TemperatureValue1;
lv_obj_t *ui_TemperatureValue2;
lv_obj_t *ui_TemperatureValue3;


// SCREEN: ui_ServiceTemperatureFridgeBack
void ui_ServiceTemperatureFridgeBack_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFridgeBack;
lv_obj_t *ui_FridgeManu2;
lv_obj_t *ui_SetPoint2;
lv_obj_t *ui_TemperatureValue4;
lv_obj_t *ui_Back14;


// SCREEN: ui_ServiceTemperatureFreezeSetpoint
void ui_ServiceTemperatureFreezeSetpoint_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFreezeSetpoint;
lv_obj_t *ui_FreezerManu;
lv_obj_t *ui_SetPoint3;
lv_obj_t *ui_TemperatureValue5;
lv_obj_t *ui_Back15;


// SCREEN: ui_ServiceTemperatureFreezerSetTem
void ui_ServiceTemperatureFreezerSetTem_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFreezerSetTem;
lv_obj_t *ui_FreezerManu1;
lv_obj_t *ui_SetPoint4;
lv_obj_t *ui_TemperatureValue6;
lv_obj_t *ui_TemperatureValue7;
lv_obj_t *ui_TemperatureValue8;


// SCREEN: ui_ServiceTemperatureFeezerBack
void ui_ServiceTemperatureFeezerBack_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFeezerBack;
lv_obj_t *ui_FreezerManu3;
lv_obj_t *ui_SetPoint5;
lv_obj_t *ui_TemperatureValue9;
lv_obj_t *ui_Back16;


// SCREEN: ui_ServiceAlarms
void ui_ServiceAlarms_screen_init(void);
lv_obj_t *ui_ServiceAlarms;
lv_obj_t *ui_Service1;
lv_obj_t *ui_Temperature3;
lv_obj_t *ui_Alarms1;
lv_obj_t *ui_Back17;
lv_obj_t *ui_DataLogging1;
lv_obj_t *ui_Calibrartion1;


// SCREEN: ui_ServiceAlarmsTemp
void ui_ServiceAlarmsTemp_screen_init(void);
lv_obj_t *ui_ServiceAlarmsTemp;
lv_obj_t *ui_Alarms3;
lv_obj_t *ui_Temperature4;
lv_obj_t *ui_Battery;
lv_obj_t *ui_Lid;
lv_obj_t *ui_Back18;
lv_obj_t *ui_MuteAlarms;


// SCREEN: ui_ServiceAlarmsTempDeviation
void ui_ServiceAlarmsTempDeviation_screen_init(void);
lv_obj_t *ui_ServiceAlarmsTempDeviation;
lv_obj_t *ui_TempDeviation;
lv_obj_t *ui_AlarmDelay;
lv_obj_t *ui_Back19;


// SCREEN: ui_ServiceAlarmsTempDeviationEnter
void ui_ServiceAlarmsTempDeviationEnter_screen_init(void);
lv_obj_t *ui_ServiceAlarmsTempDeviationEnter;
lv_obj_t *ui_TempDeviation1;
lv_obj_t *ui_TemperatureValue10;
lv_obj_t *ui_TemperatureValue11;
lv_obj_t *ui_TemperatureValue12;


// SCREEN: ui_WarningScreen
void ui_WarningScreen_screen_init(void);
lv_obj_t *ui_WarningScreen;
lv_obj_t *ui_Fridge5;
lv_obj_t *ui_WarningText;
lv_obj_t *ui_Label1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Main_screen_init();
ui_OperationModeScreenFreezer_screen_init();
ui_OperationModeScreenFridge_screen_init();
ui_OperationModeScreenBack_screen_init();
ui_SettingData_screen_init();
ui_SettingDateTime_screen_init();
ui_SettingDateTimeYear_screen_init();
ui_SettingDateTimeMonth_screen_init();
ui_SettingDateTimeDay_screen_init();
ui_SettingDateTimeHour_screen_init();
ui_SettingDateTimeMinute_screen_init();
ui_ServiceTemperature_screen_init();
ui_ServiceTemperatureFreezer_screen_init();
ui_ServiceTemperatureFridge_screen_init();
ui_ServiceTemperatureFridgeSetpoint_screen_init();
ui_ServiceTemperatureFridgeSetTem_screen_init();
ui_ServiceTemperatureFridgeBack_screen_init();
ui_ServiceTemperatureFreezeSetpoint_screen_init();
ui_ServiceTemperatureFreezerSetTem_screen_init();
ui_ServiceTemperatureFeezerBack_screen_init();
ui_ServiceAlarms_screen_init();
ui_ServiceAlarmsTemp_screen_init();
ui_ServiceAlarmsTempDeviation_screen_init();
ui_ServiceAlarmsTempDeviationEnter_screen_init();
ui_WarningScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Main);
}
