// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project


#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_SettingTemperature
void ui_SettingTemperature_screen_init(void);
lv_obj_t * ui_SettingTemperature;
lv_obj_t * ui_Settings;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_Alarm;
lv_obj_t * ui_DateTime;
lv_obj_t * ui_DataLoging;
lv_obj_t * ui_Back;

// SCREEN: ui_SettingAlarm
void ui_SettingAlarm_screen_init(void);
lv_obj_t * ui_SettingAlarm;
lv_obj_t * ui_Settings1;
lv_obj_t * ui_Temperature1;
lv_obj_t * ui_Alarm1;
lv_obj_t * ui_DateTime1;
lv_obj_t * ui_DataLoging1;
lv_obj_t * ui_Back1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SettingTemperature_screen_init();
    ui_SettingAlarm_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SettingAlarm);
}
