// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_SpeakerSymbol;
extern lv_obj_t *ui_temper;
extern lv_obj_t *ui_Freezer5;
extern lv_obj_t *ui_ac;
extern lv_obj_t *ui_BatSymbol;
// SCREEN: ui_OperationModeScreenFreezer
void ui_OperationModeScreenFreezer_screen_init(void);
extern lv_obj_t *ui_OperationModeScreenFreezer;
extern lv_obj_t *ui_OpeartionMode;
extern lv_obj_t *ui_Fridge;
extern lv_obj_t *ui_Freezer;
extern lv_obj_t *ui_Back2;
// SCREEN: ui_OperationModeScreenFridge
void ui_OperationModeScreenFridge_screen_init(void);
extern lv_obj_t *ui_OperationModeScreenFridge;
extern lv_obj_t *ui_OpeartionMode1;
extern lv_obj_t *ui_Fridge1;
extern lv_obj_t *ui_Freezer1;
extern lv_obj_t *ui_Back3;
// SCREEN: ui_OperationModeScreenBack
void ui_OperationModeScreenBack_screen_init(void);
extern lv_obj_t *ui_OperationModeScreenBack;
extern lv_obj_t *ui_OpeartionMode2;
extern lv_obj_t *ui_Fridge2;
extern lv_obj_t *ui_Freezer2;
extern lv_obj_t *ui_Back4;
// SCREEN: ui_SettingData
void ui_SettingData_screen_init(void);
extern lv_obj_t *ui_SettingData;
extern lv_obj_t *ui_SettingsDownloadData;
extern lv_obj_t *ui_DateTime1;
extern lv_obj_t *ui_DataLoging1;
extern lv_obj_t *ui_Back1;
// SCREEN: ui_SettingDateTime
void ui_SettingDateTime_screen_init(void);
extern lv_obj_t *ui_SettingDateTime;
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_DateTime;
extern lv_obj_t *ui_DownloadData;
extern lv_obj_t *ui_Back;
// SCREEN: ui_SettingDateTimeYear
void ui_SettingDateTimeYear_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeYear;
extern lv_obj_t *ui_SetYear;
extern lv_obj_t *ui_SetMonth;
extern lv_obj_t *ui_SetDay;
extern lv_obj_t *ui_Back5;
extern lv_obj_t *ui_SetHour;
extern lv_obj_t *ui_SetMinute;
// SCREEN: ui_SettingDateTimeMonth
void ui_SettingDateTimeMonth_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeMonth;
extern lv_obj_t *ui_SetYear1;
extern lv_obj_t *ui_SetMonth1;
extern lv_obj_t *ui_SetDay1;
extern lv_obj_t *ui_Back6;
extern lv_obj_t *ui_SetHour1;
extern lv_obj_t *ui_SetMinute1;
// SCREEN: ui_SettingDateTimeDay
void ui_SettingDateTimeDay_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeDay;
extern lv_obj_t *ui_SetYear2;
extern lv_obj_t *ui_SetMonth2;
extern lv_obj_t *ui_SetDay2;
extern lv_obj_t *ui_Back7;
extern lv_obj_t *ui_SetHour2;
extern lv_obj_t *ui_SetMinute2;
// SCREEN: ui_SettingDateTimeHour
void ui_SettingDateTimeHour_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeHour;
extern lv_obj_t *ui_SetYear3;
extern lv_obj_t *ui_SetMonth3;
extern lv_obj_t *ui_SetDay3;
extern lv_obj_t *ui_Back8;
extern lv_obj_t *ui_SetHour3;
extern lv_obj_t *ui_SetMinute3;
// SCREEN: ui_SettingDateTimeMinute
void ui_SettingDateTimeMinute_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeMinute;
extern lv_obj_t *ui_SetYear4;
extern lv_obj_t *ui_SetMonth4;
extern lv_obj_t *ui_SetDay4;
extern lv_obj_t *ui_Back9;
extern lv_obj_t *ui_SetHour4;
extern lv_obj_t *ui_SetMinute4;
// SCREEN: ui_ServiceTemperature
void ui_ServiceTemperature_screen_init(void);
extern lv_obj_t *ui_ServiceTemperature;
extern lv_obj_t *ui_Service;
extern lv_obj_t *ui_Temperature;
extern lv_obj_t *ui_Alarms;
extern lv_obj_t *ui_Back10;
extern lv_obj_t *ui_DataLogging;
extern lv_obj_t *ui_Calibrartion;
// SCREEN: ui_ServiceTemperatureFreezer
void ui_ServiceTemperatureFreezer_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFreezer;
extern lv_obj_t *ui_Temperature1;
extern lv_obj_t *ui_Fridge3;
extern lv_obj_t *ui_Freezer3;
extern lv_obj_t *ui_Back11;
// SCREEN: ui_ServiceTemperatureFridge
void ui_ServiceTemperatureFridge_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFridge;
extern lv_obj_t *ui_Temperature2;
extern lv_obj_t *ui_Fridge4;
extern lv_obj_t *ui_Freezer4;
extern lv_obj_t *ui_Back12;
// SCREEN: ui_ServiceTemperatureFridgeSetpoint
void ui_ServiceTemperatureFridgeSetpoint_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFridgeSetpoint;
extern lv_obj_t *ui_FridgeManu;
extern lv_obj_t *ui_SetPoint;
extern lv_obj_t *ui_TemperatureValue;
extern lv_obj_t *ui_Back13;
// SCREEN: ui_ServiceTemperatureFridgeSetTem
void ui_ServiceTemperatureFridgeSetTem_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFridgeSetTem;
extern lv_obj_t *ui_FridgeManu1;
extern lv_obj_t *ui_SetPoint1;
extern lv_obj_t *ui_TemperatureValue1;
extern lv_obj_t *ui_TemperatureValue2;
extern lv_obj_t *ui_TemperatureValue3;
// SCREEN: ui_ServiceTemperatureFridgeBack
void ui_ServiceTemperatureFridgeBack_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFridgeBack;
extern lv_obj_t *ui_FridgeManu2;
extern lv_obj_t *ui_SetPoint2;
extern lv_obj_t *ui_TemperatureValue4;
extern lv_obj_t *ui_Back14;
// SCREEN: ui_ServiceTemperatureFreezeSetpoint
void ui_ServiceTemperatureFreezeSetpoint_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFreezeSetpoint;
extern lv_obj_t *ui_FreezerManu;
extern lv_obj_t *ui_SetPoint3;
extern lv_obj_t *ui_TemperatureValue5;
extern lv_obj_t *ui_Back15;
// SCREEN: ui_ServiceTemperatureFreezerSetTem
void ui_ServiceTemperatureFreezerSetTem_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFreezerSetTem;
extern lv_obj_t *ui_FreezerManu1;
extern lv_obj_t *ui_SetPoint4;
extern lv_obj_t *ui_TemperatureValue6;
extern lv_obj_t *ui_TemperatureValue7;
extern lv_obj_t *ui_TemperatureValue8;
// SCREEN: ui_ServiceTemperatureFeezerBack
void ui_ServiceTemperatureFeezerBack_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFeezerBack;
extern lv_obj_t *ui_FreezerManu3;
extern lv_obj_t *ui_SetPoint5;
extern lv_obj_t *ui_TemperatureValue9;
extern lv_obj_t *ui_Back16;
// SCREEN: ui_ServiceAlarms
void ui_ServiceAlarms_screen_init(void);
extern lv_obj_t *ui_ServiceAlarms;
extern lv_obj_t *ui_Service1;
extern lv_obj_t *ui_Temperature3;
extern lv_obj_t *ui_Alarms1;
extern lv_obj_t *ui_Back17;
extern lv_obj_t *ui_DataLogging1;
extern lv_obj_t *ui_Calibrartion1;
// SCREEN: ui_ServiceAlarmsTemp
void ui_ServiceAlarmsTemp_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsTemp;
extern lv_obj_t *ui_Alarms3;
extern lv_obj_t *ui_Temperature4;
extern lv_obj_t *ui_Battery;
extern lv_obj_t *ui_Lid;
extern lv_obj_t *ui_Back18;
extern lv_obj_t *ui_MuteAlarms;
// SCREEN: ui_ServiceAlarmsTempDeviation
void ui_ServiceAlarmsTempDeviation_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsTempDeviation;
extern lv_obj_t *ui_TempDeviation;
extern lv_obj_t *ui_AlarmDelay;
extern lv_obj_t *ui_Back19;
// SCREEN: ui_ServiceAlarmsTempDeviationEnter
void ui_ServiceAlarmsTempDeviationEnter_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsTempDeviationEnter;
extern lv_obj_t *ui_TempDeviation1;
extern lv_obj_t *ui_TemperatureValue10;
extern lv_obj_t *ui_TemperatureValue11;
extern lv_obj_t *ui_TemperatureValue12;
// SCREEN: ui_WarningScreen
void ui_WarningScreen_screen_init(void);
extern lv_obj_t *ui_WarningScreen;
extern lv_obj_t *ui_Fridge5;
extern lv_obj_t *ui_WarningText;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_verdana244);
LV_FONT_DECLARE( ui_font_verdana364);
LV_FONT_DECLARE( ui_font_verdana404);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
