// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project


#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_SettingTemperature
void ui_SettingTemperature_screen_init(void);
extern lv_obj_t * ui_SettingTemperature;
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Alarm;
extern lv_obj_t * ui_DateTime;
extern lv_obj_t * ui_DataLoging;
extern lv_obj_t * ui_Back;
// SCREEN: ui_SettingAlarm
void ui_SettingAlarm_screen_init(void);
extern lv_obj_t * ui_SettingAlarm;
extern lv_obj_t * ui_Settings1;
extern lv_obj_t * ui_Temperature1;
extern lv_obj_t * ui_Alarm1;
extern lv_obj_t * ui_DateTime1;
extern lv_obj_t * ui_DataLoging1;
extern lv_obj_t * ui_Back1;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
